spring.application.name=crudback
spring.data.mongodb.uri= mongodb+srv://djkformeee:vczuPmXf8c94Uwl8@cluster0.lwx7d.mongodb.net/springusers?retryWrites=true&w=majority&appName=Cluster0
logging.level.org.mongodb.driver=DEBUG